# localization.py

TRANSLATIONS = {
    "he": {
        "husband_of": "בעלה של",
        "wife_of": "אשתו של",
        "father_of": "אבא של",
        "mother_of": "אמא של",
        "son_of": "בן של",
        "daughter_of": "בת של",
        "relative": "relative",
        "upcoming_hebrew_dates": "תאריכים עבריים קרובים",
        "deceased_birthday_age_details": " (נפטר בגיל {age_at_death}, {years_since_birth} שנים מאז לידתו)",
        "birthday_age": " (גיל {age})",
        "yahrzeit_age_details": " (נפטר בגיל {age_at_death}, {years_since_death} שנים לפטירתו)",
        "anniversary_divorced": " (נישאו בשנת {marriage_year})",
        "anniversary_deceased": " (היו נשואים {marriage_duration} שנים)",
        "anniversary_married": " (נשואים: {years_married} שנים)",
        "event_header": "#### **{emoji} {hebrew_weekday}, {original_date_str_parsed}**\n",
        "event_type_label": "* **אירוע**: `{event_name}`\n",
        "person_family_label": "* **אדם/משפחה**: `{name}{age_str}`\n",
        "distance_label": "* **מרחק**: `{dist}`\n",
        "path_label": "* **נתיב**: `{readable_path}`\n",
        "issue_title": "תאריכים עבריים קרובים",
        "monday": "יום שני",
        "tuesday": "יום שלישי",
        "wednesday": "יום רביעי",
        "thursday": "יום חמישי",
        "friday": "יום שישי",
        "saturday": "שבת",
        "sunday": "יום ראשון",
        "birt": "יום הולדת",
        "deat": "יארצייט",
        "marr": "יום נישואין",
    },
    "en": {
        "husband_of": "husband of",
        "wife_of": "wife of",
        "father_of": "father of",
        "mother_of": "mother of",
        "son_of": "son of",
        "daughter_of": "daughter of",
        "relative": "relative",
        "upcoming_hebrew_dates": "Upcoming Hebrew Dates",
        "deceased_birthday_age_details": " (died at age {age_at_death}, {years_since_birth} years since birth)",
        "birthday_age": " (age {age})",
        "yahrzeit_age_details": " (died at age {age_at_death}, {years_since_death} years since death)",
        "anniversary_divorced": " (married in {marriage_year})",
        "anniversary_deceased": " (were married for {marriage_duration} years)",
        "anniversary_married": " (married for {years_married} years)",
        "event_header": "#### **{emoji} {hebrew_weekday}, {original_date_str_parsed}**\n",
        "event_type_label": "* **Event**: `{event_name}`\n",
        "person_family_label": "* **Person/Family**: `{name}{age_str}`\n",
        "distance_label": "* **Distance**: `{dist}`\n",
        "path_label": "* **Path**: `{readable_path}`\n",
        "issue_title": "Upcoming Hebrew Dates",
        "monday": "Monday",
        "tuesday": "Tuesday",
        "wednesday": "Wednesday",
        "thursday": "Thursday",
        "friday": "Friday",
        "saturday": "Saturday",
        "sunday": "Sunday",
        "birt": "Birthday",
        "deat": "Yahrzeit",
        "marr": "Anniversary",
    }
}

def get_translation(lang, key, **kwargs):
    """
    Retrieves a translated string for a given key and language.
    """
    return TRANSLATIONS.get(lang, TRANSLATIONS["he"]).get(key, key).format(**kwargs)
